apiVersion: v1
kind: ReplicationController

metadata:
  name: nginx-rc
  labels:
    app: nginx-replicaController

spec:
  replicas: 5
  selector:
    app.kubernates.io/name: nginx-pod
    app.kubernates.io/scope: production
    app.kubernates.io/created-by: ahmad
  template:
    # here we use pod manifest as replicaset template
    metadata:
      labels:
        app.kubernates.io/name: nginx-pod
        app.kubernates.io/scope: production
        app.kubernates.io/created-by: ahmad
        app.kubernates.io/part-of: myapp
        app.kubernates.io/env: product
        app.kubernates.io/repository: myapp-repo
        app.kubernates.io/version: !!str 1.21.6
    spec:
      restartPolicy: Always
      containers:
        - name: nginx-rc-container
          image: nginx:alpine
          ports:
            - containerPort: 80
