apiVersion: v1
kind: Secret

metadata:
  name: my-secrets

type: Opaque

data:
  password: bXlwYXNzd29yZA== # should be in base64

---

apiVersion: v1
kind: Secret

metadata:
  name: my-secrets

type: Opaque

stringData:
  password: mypassword


# kubectl create secret generic mysql-secret --from-literal=MYAQL_ROOT_PASSWORD=test --from-literal=MYSQL_USER=myuser --from-literal=MYSQL_PASSWORD=mypass

# kubectl get secret mysql-secret -o yaml  ##>> echo -n bXlwYXNzd29yZA== | base64 -d


  