apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: alpine-volume-0.5g-pvc
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  volumeMode: FileSystem  # Block
  storageClassName: ""
